version: '3'

services:
    nodejs-app:
        build:
          context: ./server
          dockerfile: Dockerfile-server
        container_name: assembleserver
        hostname: assembleserver
        ports:
            - "3000:3000" 
        volumes:
            - ./server:/server 
            - /server/node_modules
        networks:
            - assemble-net
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017" 
        networks:
            - assemble-net 
    nginx:
        build:
          context: ./nginx
          dockerfile: Dockerfile-nginx
        container_name: proxy
        hostname: proxy
        ports:
            - "81:81" 
        depends_on:
            - nodejs-app
        networks:
            - assemble-net

networks:
  assemble-net:
    driver: bridge
